const { v4: uuidv4 } = require('uuid');
const prisma = require('../../models/prisma');
const ConflictError = require('../../middlewares/custom_errors/conflict_error');
const { getSuccessMessage } = require('../../middlewares/custom_success/sucess_message');

exports.getAllFoodSubcategories = async (req, res) => res.status(200).send(getSuccessMessage(200, await prisma.foodsubcategory.findMany({ orderBy: { subcategory_name: 'asc' } })));
exports.getSingleFoodSubcategory = async (req, res) => { const row = await prisma.foodsubcategory.findUnique({ where: { foodsubcategory_id: req.params.id } }); return row ? res.status(200).send(getSuccessMessage(200, row)) : res.status(404).json({ error: 'Subcategory not found' }); };
exports.createFoodSubcategory = async (req, res) => { const data = req.body; if (await prisma.foodsubcategory.findUnique({ where: { subcategory_name: data.subcategory_name } })) throw new ConflictError('Subcategory exists'); const row = await prisma.foodsubcategory.create({ data: { ...data, foodsubcategory_id: data.foodsubcategory_id || uuidv4() } }); res.status(201).send(getSuccessMessage(201, row)); };
exports.updateFoodSubcategory = async (req, res) => { const id = req.params.id; const data = req.body; if (await prisma.foodsubcategory.findFirst({ where: { subcategory_name: data.subcategory_name, foodsubcategory_id: { not: id } } })) throw new ConflictError('Subcategory name already exists'); const exists = await prisma.foodsubcategory.findUnique({ where: { foodsubcategory_id: id } }); if (!exists) return res.status(404).json({ error: 'Subcategory not found' }); await prisma.foodsubcategory.update({ data, where: { foodsubcategory_id: id } }); return res.status(200).send(getSuccessMessage(200, { id, ...data })); };
exports.deleteFoodSubcategory = async (req, res) => { const exists = await prisma.foodsubcategory.findUnique({ where: { foodsubcategory_id: req.params.id } }); if (!exists) return res.status(404).json({ error: 'Subcategory not found' }); await prisma.foodsubcategory.delete({ where: { foodsubcategory_id: req.params.id } }); return res.status(204).send(); };
