const prisma = require('../../models/prisma');
const ConflictError = require('../../middlewares/custom_errors/conflict_error');
const { getSuccessMessage } = require('../../middlewares/custom_success/sucess_message');

exports.getAllMealplanTimes = async (req, res) => res.status(200).send(getSuccessMessage(200, await prisma.mealplantime.findMany({ orderBy: { idmealPlanWeek: 'asc' } }), 'Successfully retrieved'));
exports.getMealplanTime = async (req, res) => { const row = await prisma.mealplantime.findUnique({ where: { idmealPlanWeek: Number(req.params.id) } }); return row ? res.json(row) : res.status(404).json({ message: 'Meal plan time resource does not exist' }); };
exports.createMealplanTime = async (req, res) => { const name = req.body.mealPlanName; if (await prisma.mealplantime.findUnique({ where: { meal_plan_name: name } })) throw new ConflictError('Meal plan with the same name already exists'); await prisma.mealplantime.create({ data: { meal_plan_name: name, owner_user_id: req.userId, plan_goal: req.body.planGoal || 'balanced', description: req.body.description || null, budget_level: req.body.budgetLevel || 'standard', estimated_cost: req.body.estimatedCost || null, currency: req.body.currency || 'KES', image_url: req.body.imageUrl || null } }); res.status(201).send(getSuccessMessage(201, [], 'Successfully created a meal plan time interval')); };
exports.updateMealplanTime = async (req, res) => { const id = Number(req.params.id); const name = req.body.mealPlanName; if (await prisma.mealplantime.findFirst({ where: { meal_plan_name: name, idmealPlanWeek: { not: id } } })) throw new ConflictError('Meal plan time with the same name already exists'); await prisma.mealplantime.update({ data: { meal_plan_name: name }, where: { idmealPlanWeek: id } }); res.status(200).send(getSuccessMessage(200, [], 'Successfully updated')); };
exports.deleteMealplanTime = async (req, res) => { await prisma.mealplantime.delete({ where: { idmealPlanWeek: Number(req.params.id) } }); res.status(200).send(getSuccessMessage(200, [], 'Deleted successfully')); };
