import { FormEvent, useState } from "react"
import type { Catalog, Country, FoodItem } from "../api"
import { useCreateCountryMutation, useDeleteCountryMutation, useLinkCountryFoodMutation, useLinkCountryMealMutation, useUpdateCountryMutation } from "../store/mealPlanApi"

type Props = { catalog: Catalog; onFood: (food: FoodItem) => void; canManage?: boolean; offline?: boolean; notify?: (kind: "success" | "error", message: string) => void }
const errorMessage = (error: unknown) => { const response = error as { data?: { message?: string; errors?: { message?: string } } }; return response.data?.message || response.data?.errors?.message || "Could not save this country." }

export default function CountryExplorer({ catalog, onFood, canManage = false, offline = false, notify }: Props) {
  const [selected, setSelected] = useState<Country | null>(null); const [editing, setEditing] = useState<Country | "new" | null>(null); const [foodItemId, setFoodItemId] = useState(""); const [mealTypeId, setMealTypeId] = useState(""); const [deleteCountry, deleteState] = useDeleteCountryMutation(); const [linkFood, linkFoodState] = useLinkCountryFoodMutation(); const [linkMeal, linkMealState] = useLinkCountryMealMutation()
  const foods = selected ? catalog.foodItems.filter(food => food.countries?.some(country => country.id === selected.id)) : []
  const meals = selected ? catalog.mealTypes.filter(meal => meal.countries?.some(country => country.id === selected.id)) : []
  const availableFoods = selected ? catalog.foodItems.filter(food => !food.countries?.some(country => country.id === selected.id)) : []
  const availableMeals = selected ? catalog.mealTypes.filter(meal => !meal.countries?.some(country => country.id === selected.id)) : []
  const remove = async (country: Country) => { if (!window.confirm(`Delete ${country.name}? This is only allowed when it has no linked foods or meals.`)) return; try { await deleteCountry(country.id).unwrap(); if (selected?.id === country.id) setSelected(null); notify?.("success", `${country.name} was deleted.`) } catch (error) { notify?.("error", errorMessage(error)) } }
  const attachFood = async () => { if (!selected || !foodItemId) return; try { await linkFood({ countryId: selected.id, foodItemId }).unwrap(); setFoodItemId(""); notify?.("success", `Food item added to ${selected.name}.`) } catch (error) { notify?.("error", errorMessage(error)) } }
  const attachMeal = async () => { if (!selected || !mealTypeId) return; try { await linkMeal({ countryId: selected.id, mealTypeId }).unwrap(); setMealTypeId(""); notify?.("success", `Meal added to ${selected.name}.`) } catch (error) { notify?.("error", errorMessage(error)) } }
  return <section className="country-section" id="countries">
    <div className="section-heading"><div><span className="eyebrow">Food around the world</span><h2>{canManage ? "Manage countries" : "Explore by country"}</h2><p className="section-copy">{canManage ? "Add and maintain the places connected to foods and meals." : "Discover foods and meals through the places they come from."}</p></div>{canManage && <button className="primary" onClick={() => setEditing("new")} disabled={offline}>＋ Country</button>}</div>
    <div className="country-grid">{catalog.countries.map(country => <article className="country-card" key={country.id}><button className="country-explore" onClick={() => setSelected(country)}><span>{country.code}</span><h3>{country.name}</h3><p>{country.description || "No description added yet."}</p><b>Explore food →</b></button>{canManage && <div className="country-actions"><button onClick={() => setEditing(country)} disabled={offline}>Edit</button><button className="danger-link" onClick={() => remove(country)} disabled={offline || deleteState.isLoading}>Delete</button></div>}</article>)}</div>
    {!catalog.countries.length && <div className="no-results"><span>◎</span><h3>No countries yet</h3><p>{canManage ? "Add the first country to begin organising food by origin." : "Countries will appear here once they have been added."}</p></div>}
    {selected && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setSelected(null)}><div className="modal country-modal"><button className="close" onClick={() => setSelected(null)}>×</button><span className="eyebrow">{selected.code} · Food culture</span><h2>{selected.name}</h2><p className="modal-copy">{selected.description || "No description added yet."}</p>{canManage && <div className="country-link-panel"><h3>Add existing items</h3><div className="country-link-row"><select value={foodItemId} onChange={event => setFoodItemId(event.target.value)}><option value="">Choose a food item…</option>{availableFoods.map(food => <option key={food.food_itemID} value={food.food_itemID}>{food.food_name}</option>)}</select><button className="secondary" onClick={attachFood} disabled={!foodItemId || linkFoodState.isLoading || offline}>{linkFoodState.isLoading ? "Adding…" : "Add food"}</button></div><div className="country-link-row"><select value={mealTypeId} onChange={event => setMealTypeId(event.target.value)}><option value="">Choose a meal…</option>{availableMeals.map(meal => <option key={meal.mealTypesID} value={meal.mealTypesID}>{meal.meal_name}</option>)}</select><button className="secondary" onClick={attachMeal} disabled={!mealTypeId || linkMealState.isLoading || offline}>{linkMealState.isLoading ? "Adding…" : "Add meal"}</button></div>{!availableFoods.length && !availableMeals.length && <p className="muted">Every catalog item is already linked to this country.</p>}</div>}<h3>Foods grown or used here</h3>{foods.length ? <div className="mini-grid">{foods.map(food => <button key={food.food_itemID} onClick={() => onFood(food)}>{food.food_name}<span>View details →</span></button>)}</div> : <p className="muted">No foods have been linked yet.</p>}<h3>Meals from {selected.name}</h3>{meals.length ? <div className="mini-grid">{meals.map(meal => <div key={meal.mealTypesID}>{meal.meal_name}<span>{catalog.recipes.filter(recipe => recipe.meal_typeID === meal.mealTypesID).length} recipes</span></div>)}</div> : <p className="muted">No meals have been linked yet.</p>}</div></div>}
    {editing && <CountryForm country={editing === "new" ? undefined : editing} close={() => setEditing(null)} done={message => { setEditing(null); notify?.("success", message) }} fail={message => notify?.("error", message)} />}
  </section>
}

function CountryForm({ country, close, done, fail }: { country?: Country; close: () => void; done: (message: string) => void; fail: (message: string) => void }) {
  const [name, setName] = useState(country?.name || ""); const [code, setCode] = useState(country?.code || ""); const [description, setDescription] = useState(country?.description || ""); const [imageUrl, setImageUrl] = useState(country?.image_url || "")
  const [createCountry, createState] = useCreateCountryMutation(); const [updateCountry, updateState] = useUpdateCountryMutation(); const busy = createState.isLoading || updateState.isLoading
  const submit = async (event: FormEvent) => { event.preventDefault(); const body = { name: name.trim(), code: code.trim().toUpperCase(), description: description.trim() || undefined, image_url: imageUrl.trim() || undefined }; try { if (country) await updateCountry({ id: country.id, body }).unwrap(); else await createCountry(body).unwrap(); done(country ? `${body.name} was updated.` : `${body.name} was added.`) } catch (error) { fail(errorMessage(error)) } }
  return <div className="modal-backdrop" onMouseDown={event => event.target === event.currentTarget && close()}><form className="modal compact" onSubmit={submit}><button type="button" className="close" onClick={close}>×</button><span className="eyebrow">Country directory</span><h2>{country ? "Edit country" : "Add country"}</h2><p className="modal-copy">Use a unique name and a two- or three-letter country code.</p><div className="stack-fields"><label><span>Name</span><input autoFocus required maxLength={100} value={name} onChange={event => setName(event.target.value)} placeholder="e.g. Kenya" /></label><label><span>Code</span><input required minLength={2} maxLength={3} pattern="[A-Za-z]{2,3}" value={code} onChange={event => setCode(event.target.value.toUpperCase())} placeholder="KEN" /></label><label><span>Description <small>optional</small></span><textarea value={description} onChange={event => setDescription(event.target.value)} /></label><label><span>Image URL <small>optional</small></span><input type="url" value={imageUrl} onChange={event => setImageUrl(event.target.value)} placeholder="https://…" /></label></div><div className="modal-actions"><span/><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy ? "Saving…" : country ? "Save changes" : "Add country"}</button></div></form></div>
}
