import { FormEvent, useState } from "react"
import type { Catalog } from "../api"
import { useSaveTaxonomyMutation } from "../store/mealPlanApi"
export default function TaxonomyManager({ catalog }: { catalog: Catalog }) {
  const [editing, setEditing] = useState<{ kind: 'category' | 'subcategory'; id: string; name: string; description: string; category: string; image: string } | null>(null)
  const [save, state] = useSaveTaxonomyMutation(); const [error, setError] = useState('')
  const fail = (e: unknown) => setError((e as { data?: { message?: string; error?: string } }).data?.message || (e as { data?: { error?: string } }).data?.error || 'Could not update. Check whether this category is in use.')
  const remove = async (kind: 'category' | 'subcategory', id: string, name: string) => { if (!window.confirm(`Delete ${name}? Categories in use cannot be deleted.`)) return; setError(''); try { await save({ kind, id }).unwrap() } catch (e) { fail(e) } }
  const submit = async (e: FormEvent) => { e.preventDefault(); if (!editing) return; setError(''); const body = editing.kind === 'category' ? { categoryName: editing.name, description: editing.description, imageURL: editing.image } : { subcategory_name: editing.name, description: editing.description, food_category_id: editing.category }; try { await save({ kind: editing.kind, id: editing.id, body }).unwrap(); setEditing(null) } catch (e) { fail(e) } }
  return <section><details><summary>Manage categories and subcategories</summary>{catalog.categories.map(c => <div key={c.food_categoryID}><h3>{c.category_name}</h3><button onClick={() => setEditing({ kind: 'category', id: c.food_categoryID, name: c.category_name, description: c.description || '', category: '', image: c.image_url || '' })}>Edit category</button><button disabled={state.isLoading} onClick={() => remove('category', c.food_categoryID, c.category_name)}>Delete category</button><ul>{catalog.subcategories.filter(s => s.food_category_id === c.food_categoryID).map(s => <li key={s.foodsubcategory_id}>{s.subcategory_name} <button onClick={() => setEditing({ kind: 'subcategory', id: s.foodsubcategory_id, name: s.subcategory_name, description: s.description || '', category: c.food_categoryID, image: '' })}>Edit</button><button disabled={state.isLoading} onClick={() => remove('subcategory', s.foodsubcategory_id, s.subcategory_name)}>Delete</button></li>)}</ul></div>)}</details>{error && !editing && <p role="alert">{error}</p>}{editing && <div className="modal-backdrop"><form className="modal compact" onSubmit={submit}><h2>Edit {editing.kind}</h2><div className="stack-fields"><label><span>Name</span><input required maxLength={45} value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })} /></label><label><span>Description</span><textarea value={editing.description} onChange={e => setEditing({ ...editing, description: e.target.value })} /></label>{editing.kind === 'subcategory' ? <label><span>Category</span><select value={editing.category} onChange={e => setEditing({ ...editing, category: e.target.value })}>{catalog.categories.map(c => <option key={c.food_categoryID} value={c.food_categoryID}>{c.category_name}</option>)}</select></label> : <label><span>Image URL</span><input type="url" value={editing.image} onChange={e => setEditing({ ...editing, image: e.target.value })} /></label>}</div>{error && <p role="alert">{error}</p>}<div className="modal-actions"><button type="button" onClick={() => setEditing(null)}>Cancel</button><button disabled={state.isLoading}>Save</button></div></form></div>}</section>
}
