const { v4: uuidv4 } = require('uuid');
const prisma = require('../../models/prisma');
const include = { meals: true, mealtype: true };
const flatten = row => ({ meal_mealTypeID: row.meal_mealTypeID, mealName: row.meals?.mealName, mealId: row.meals?.mealID, meal_name: row.mealtype?.meal_name, mealTypesId: row.mealtype?.mealTypesID });
exports.getAllMealMealTypes = async (req, res) => res.json((await prisma.mealmealtype.findMany({ include })).map(flatten));
exports.getMealSelection = async (req, res) => res.json({ meals: await prisma.meals.findMany({ select: { mealID: true, mealName: true } }), mealTypes: await prisma.mealtype.findMany({ select: { mealTypesID: true, meal_name: true } }) });
exports.createMealInsertion = async (req, res) => { await prisma.mealmealtype.create({ data: { meal_mealTypeID: uuidv4(), mealsID: req.body.mealsId, mealTypeID: req.body.mealTypeId } }); res.json({ success: true }); };
exports.getSingleItem = async (req, res) => { const row = await prisma.mealmealtype.findUnique({ where: { meal_mealTypeID: req.params.id }, include }); res.json({ mealMealType: row && flatten(row) }); };
exports.updateSingleItem = async (req, res) => { await prisma.mealmealtype.update({ data: { mealsID: req.body.mealsId, mealTypeID: req.body.mealTypeId }, where: { meal_mealTypeID: req.params.id } }); res.json({ success: true }); };
exports.deleteSingleItem = async (req, res) => { await prisma.mealmealtype.delete({ where: { meal_mealTypeID: req.params.id } }); res.json({ success: true }); };
