import { FormEvent, useState } from "react"
import { useDispatch, useSelector } from "react-redux"
import type { RootState } from "./store"
import { clearCredentials, setCredentials } from "./features/auth/authSlice"
import { useCreateUserMutation, useGetUsersQuery, useLoginMutation, useLogoutMutation, useRegisterMutation, useUpdateUserMutation } from "./features/auth/authApi"

export function AuthGate() {
  const [open, setOpen] = useState(false)
  return <main className="auth-gate"><div className="auth-gate-copy"><a className="brand" href="/" aria-label="Plateful home"><span className="brand-mark">P</span><span>plateful</span></a><span className="eyebrow">Meal planning, made personal</span><h1>Plan better meals.<br/>Live a little lighter.</h1><p>Build thoughtful weekly meal plans, keep your ingredients organised, and turn good intentions into a nourishing routine.</p><div className="auth-gate-actions"><button className="primary" onClick={()=>setOpen(true)}>Sign in to continue</button><span>New members can create an account in the next step.</span></div></div><div className="auth-gate-art"><div className="plate"><span>✦</span><strong>Your week,<br/>beautifully planned.</strong></div><div className="floating-card one">7 days <span>in balance</span></div><div className="floating-card two">35 meals <span>with purpose</span></div></div>{open&&<AuthModal close={()=>setOpen(false)}/>}</main>
}

export function AccountButton() {
  const user = useSelector((state: RootState) => state.auth.user); const dispatch = useDispatch(); const [open,setOpen]=useState(false); const [logout]=useLogoutMutation()
  if (!user) return <><button className="account-button" onClick={() => setOpen(true)}>Sign in</button>{open&&<AuthModal close={()=>setOpen(false)}/>}</>
  const dashboard = user.role === "admin" ? "/admin" : user.role === "professional" ? "/professional" : "/"
  return <><button className="account-button signed" onClick={() => setOpen(true)}><span>{user.email.slice(0,1).toUpperCase()}</span><div><strong>{user.email}</strong><small>{user.role}</small></div></button>{open && <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><div className="modal compact"><button className="close" onClick={()=>setOpen(false)}>×</button><span className="eyebrow">Your workspace</span><h2>{user.role === "admin" ? "Administrator" : user.role === "professional" ? "Meal professional" : "Member"}</h2><p className="modal-copy">Signed in as {user.email}</p>{user.role !== "user" && <a className="primary workspace-link" href={dashboard}>Open dashboard</a>}<button className="danger" onClick={async()=>{await logout();dispatch(clearCredentials());setOpen(false)}}>Sign out</button></div></div>}</>
}

export function AuthModal({ close }: { close:()=>void }) {
  const [registering,setRegistering]=useState(false); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const dispatch=useDispatch(); const [login,{isLoading:l}]=useLoginMutation(); const [register,{isLoading:r}]=useRegisterMutation()
  const submit=async(e:FormEvent)=>{e.preventDefault();setError("");try{const result=registering?await register({userEmail:email,password,confirm_password:password}).unwrap():await login({userEmail:email,password}).unwrap();dispatch(setCredentials(result));close()}catch(err){const data=(err as {data?:{message?:string;error?:string}}).data;setError(data?.message||data?.error||"Could not sign in")}}
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="modal compact" onSubmit={submit}><button type="button" className="close" onClick={close}>×</button><span className="eyebrow">{registering?"Join Plateful":"Welcome back"}</span><h2>{registering?"Create your account":"Sign in"}</h2><p className="modal-copy">{registering?"Start building meal plans that work for you.":"Continue to your meal-planning workspace."}</p><div className="stack-fields"><label><span>Email</span><input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label><span>Password</span><input type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)}/></label></div>{error&&<p className="auth-error">{error}</p>}<div className="auth-switch"><button type="button" onClick={()=>setRegistering(!registering)}>{registering?"Already have an account? Sign in":"New here? Create an account"}</button><button className="primary" disabled={l||r}>{l||r?"Please wait…":registering?"Create account":"Sign in"}</button></div></form></div>
}

export function AdminPanel() {
  const user=useSelector((state:RootState)=>state.auth.user); const {data:users=[],isLoading}=useGetUsersQuery(undefined,{skip:user?.role!=="admin"}); const [update]=useUpdateUserMutation(); const [create]=useCreateUserMutation(); const [showCreate,setShowCreate]=useState(false)
  if(user?.role!=="admin")return null
  return <section className="admin-panel" id="admin"><div className="section-heading"><div><span className="eyebrow">Administration</span><h2>People & access</h2></div><button className="primary" onClick={()=>setShowCreate(true)}>＋ Add user</button></div>{isLoading?<div className="loading"><span/></div>:<div className="users-table"><div className="user-row header"><span>Account</span><span>Role</span><span>Status</span><span>Action</span></div>{users.map(item=><div className="user-row" key={item.id}><span><strong>{item.email}</strong><small>#{item.id}</small></span><select value={item.role} onChange={e=>update({id:item.id,role:e.target.value})}><option value="user">Member</option><option value="professional">Professional</option><option value="admin">Admin</option></select><span className={`status ${item.status}`}>{item.status}</span><button className="secondary" disabled={item.id===user.id} onClick={()=>update({id:item.id,status:item.status==="revoked"?"active":"revoked"})}>{item.status==="revoked"?"Restore":"Revoke"}</button></div>)}</div>}{showCreate&&<CreateUser close={()=>setShowCreate(false)} create={create}/>}</section>
}

function CreateUser({close,create}:{close:()=>void;create:ReturnType<typeof useCreateUserMutation>[0]}){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[role,setRole]=useState("user");const submit=async(e:FormEvent)=>{e.preventDefault();await create({email,password,role}).unwrap();close()};return <div className="modal-backdrop"><form className="modal compact" onSubmit={submit}><button type="button" className="close" onClick={close}>×</button><span className="eyebrow">Administrator action</span><h2>Create an account</h2><div className="stack-fields"><label><span>Email</span><input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label><span>Temporary password</span><input type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)}/></label><label><span>Role</span><select value={role} onChange={e=>setRole(e.target.value)}><option value="user">Member</option><option value="professional">Professional</option><option value="admin">Administrator</option></select></label></div><div className="modal-actions"><span/><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">Create</button></div></form></div>}
