const { v4: uuidv4 } = require('uuid');
const prisma = require('../../models/prisma');

async function withFoodItems(recipe) {
  if (!recipe) return recipe;
  const links = await prisma.recipe_food_items.findMany({ where: { recipe_id: recipe.recipe_ID } });
  const foods = await prisma.fooditems.findMany({ where: { food_itemID: { in: links.map(link => link.food_item_id) } } });
  return { ...recipe, foodItems: foods.map(food => ({ ...food, RecipeFoodItem: links.find(link => link.food_item_id === food.food_itemID) })) };
}
exports.list = async (req, res) => res.json({ recipes: await Promise.all((await prisma.recipe.findMany({ orderBy: { title: 'asc' } })).map(withFoodItems)) });
exports.create = async (req, res) => { const { foodItems = [], ...data } = req.body; const recipe = await prisma.$transaction(async tx => { const created = await tx.recipe.create({ data: { ...data, recipe_ID: data.recipe_ID || uuidv4(), owner_user_id: req.userId } }); if (foodItems.length) await tx.recipe_food_items.createMany({ data: foodItems.map(item => ({ recipe_id: created.recipe_ID, food_item_id: item.id, quantity: item.quantity, notes: item.notes })) }); return created; }); res.status(201).json({ recipe: await withFoodItems(recipe) }); };
exports.update = async (req, res) => { const id = Number(req.params.id); const recipe = await prisma.recipe.findUnique({ where: { idrecipe: id } }); if (!recipe) return res.sendStatus(404); if (req.roles !== 'admin' && recipe.owner_user_id !== req.userId) return res.status(403).json({ message: 'You can only edit recipes that you created' }); const { foodItems, ...data } = req.body; const updated = await prisma.$transaction(async tx => { const row = await tx.recipe.update({ data, where: { idrecipe: id } }); if (foodItems) { await tx.recipe_food_items.deleteMany({ where: { recipe_id: recipe.recipe_ID } }); if (foodItems.length) await tx.recipe_food_items.createMany({ data: foodItems.map(item => ({ recipe_id: recipe.recipe_ID, food_item_id: item.id, quantity: item.quantity, notes: item.notes })) }); } return row; }); res.json({ recipe: await withFoodItems(updated) }); };
exports.remove = async (req, res) => { const id = Number(req.params.id); const recipe = await prisma.recipe.findUnique({ where: { idrecipe: id } }); if (!recipe) return res.sendStatus(404); if (req.roles !== 'admin' && recipe.owner_user_id !== req.userId) return res.status(403).json({ message: 'You can only delete recipes that you created' }); await prisma.$transaction([prisma.recipe_food_items.deleteMany({ where: { recipe_id: recipe.recipe_ID } }), prisma.recipe.delete({ where: { idrecipe: id } })]); res.sendStatus(204); };
